### ISSUE TITLE
cambiar las funciones de "date to string" para que la función para ser generadas desde date

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/best-globals#5]
date ahora es una función que recibe un Date, lo valida y completa (para generar un objeto igual al que genera date.iso y los otros constructores). 

Esos objetos generados son Dates a los que se les agregan algunas funciones, por ejemplo: toYmd, toHms, etc que reemplazan a ymdString, etc.

Además se crea la función datetime que hace lo mismo que date salvo por el hecho de que datetime no impide que haya hora, minutos y segundos.

También existe timeinterval(int).toHms para formatear un intervalo de tiempo. La función timeinterval puede generar un objeto TimeInterval con la función toHms y todas las que necesitemos en otros módulos.

Puse casos de prueba en un branch llamado date-time

**Comment by diegoefe** [comment]
Ya debería estar
