### ISSUE TITLE
Mejorar la complejidad invirtiendo la lógica de isValidDate

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/best-globals#7]
Revisando https://codeclimate.com/github/codenautas/best-globals/best-globals.js veo que esa es una de las funciones con más complejidad. 

Lo que hace es ver si con los parámetros y,m,d se puede construir una fecha que finalmente tenga y,m,d de valores (no alcanza con ver que se pueda construir una fecha válida porque podría tener otro mes si se le pasa 31 de abril lo podría tomar como 1 de mayo). 

Proponogo que la comprobación en vez de hacerse antes se haga después de crear el Date (verificando que el año, mes y día que efectivamente tiene el date coincida con los parámetros). Eso mejora mucho la complejidad.

**Comment by diegoefe** [comment]
Buena idea. Asumimos entonces que crear siempre un Date() es barato, no?
